#redis/redis-stack contains both Redis Stack server 
# and RedisInsight to visualize your data.
# https://hub.docker.com/r/redis/redis-stack-server
services:
  redis:
    image: redis/redis-stack
    ports:
      - '6379:6379'
      - '8001:8001'